
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Richard Cui
 */
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;


public class PM_LoginScreen extends javax.swing.JFrame {

    private FileWriter fw;
    private PrintWriter pw;
    public String loginName;
    public String loginPass;
    public String textFileName;

    //method to remove trailing whitespace
    public String removeTrailSpace(String s) {
        int len = s.length();
        for(;len>0;len--) {
            if(!Character.isWhitespace(s.charAt(len-1))) break;
        }
        return s.substring(0,len);      
    }
    
    
    //method to remove trailing space and create file name
    public String tfileName(String u, String p) {
        int len = u.length();
        for(;len>0;len--) {
            if(!Character.isWhitespace(u.charAt(len-1))) break;
        }
        u = u.substring(0,len);
        return u+ "-" + p + ".txt";
    }
    /**
     * Creates new form PM_LoginScreen
     */
    public PM_LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        loginWelcomeLabel = new javax.swing.JLabel();
        loginUsernameTextField = new javax.swing.JTextField();
        loginUsernameLabel = new javax.swing.JLabel();
        loginPasswordLabel = new javax.swing.JLabel();
        quitButton = new javax.swing.JButton();
        loginPasswordTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        createAccountButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        loginIcon = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("WELCOME!");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SUPREME PASSWORD MANAGER LOGIN");
        setLocation(new java.awt.Point(500, 100));

        loginWelcomeLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        loginWelcomeLabel.setText("Welcome User! Please Log In or Create an Account");

        loginUsernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextFieldActionPerformed(evt);
            }
        });

        loginUsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginUsernameLabel.setText("Username:");

        loginPasswordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginPasswordLabel.setText("Password:");

        quitButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        quitButton.setText("Quit Application");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        loginPasswordTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginButton.setText("Log In");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        createAccountButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createAccountButton.setText("Create An Account");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/passwordicon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loginButton)
                                .addGap(30, 30, 30)
                                .addComponent(createAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(loginUsernameLabel)
                                        .addComponent(loginPasswordLabel))
                                    .addGap(55, 55, 55)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(loginPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loginUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(loginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(quitButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginWelcomeLabel)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginWelcomeLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(loginIcon))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginUsernameLabel))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginPasswordLabel)
                            .addComponent(loginPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginButton)
                            .addComponent(createAccountButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(quitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
        // quit button to exit the application
    }//GEN-LAST:event_quitButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String userName = loginUsernameTextField.getText(); 
        String password = loginPasswordTextField.getText();
        ArrayList<String> fileList = new ArrayList<>();
        
        textFileName = tfileName(userName,password);
        
        File folder = new File("src/userAccounts/");
        
        File[] listofFiles = folder.listFiles();
        for(File file : listofFiles) {
            if(file.isFile()) {
                fileList.add(file.getName());
            }
        }
        
        if(fileList.contains(textFileName)) {
            // save to text file of last login user credentials
            try {
                this.fw = new FileWriter("src/lastUserLogin.txt",true);
                this.pw = new PrintWriter(this.fw);
                this.pw.println(textFileName);
                this.pw.close();
            }
            catch(IOException ex) {
                Logger.getLogger(PM_MainScreen.class.getName()).log(Level.SEVERE,null,ex);
            }
            //FileException not used here as file is already caught
            JOptionPane.showMessageDialog(this, "Login Successful!");
            this.setVisible(false);
            new PM_MainScreen().setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "User Not Found");
            loginUsernameTextField.setText("");
            loginPasswordTextField.setText("");
        }
        // code to check if username & password matches any file in database
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextFieldActionPerformed
        // nothing to use here
    }//GEN-LAST:event_loginUsernameTextFieldActionPerformed

    
    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        String userName = loginUsernameTextField.getText();
        String password = loginPasswordTextField.getText();
        
        //remove trailing spaces from username
        userName = removeTrailSpace(userName);
        
        //if-else statement to read text fields and more
        if(userName.length()>0 && password.length()>0) {   
            try {
                String fileName= userName + "-" + password + ".txt";
                String dirName = "src/userAccounts/";
                File dir = new File(dirName);
                File userFile = new File(dir,fileName);
                if(userFile.createNewFile()) {
                    JOptionPane.showMessageDialog(this, "File Created:  " + fileName + "\nWelcome, New User!");
                    this.setVisible(false);
                    new PM_MainScreen().pack();
                    new PM_MainScreen().setLocationRelativeTo(null);
                    new PM_MainScreen().setVisible(true);
                }
                else {
                    JOptionPane.showMessageDialog(this, "User Already Exists!");
                    loginUsernameTextField.setText("");
                    loginPasswordTextField.setText("");
                }                             
            }
            catch(IOException ex) {
                Logger.getLogger(PM_MainScreen.class.getName()).log(Level.SEVERE,null,ex);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Enter a valid username and password.");
        }
    }//GEN-LAST:event_createAccountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PM_LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PM_LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PM_LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PM_LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PM_LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton createAccountButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton loginButton;
    private javax.swing.JLabel loginIcon;
    private javax.swing.JLabel loginPasswordLabel;
    public javax.swing.JPasswordField loginPasswordTextField;
    private javax.swing.JLabel loginUsernameLabel;
    public javax.swing.JTextField loginUsernameTextField;
    private javax.swing.JLabel loginWelcomeLabel;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables
}
